// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOgcvxQOF4OOc_d_O5RLOsTnPNYGqJlY',
    appId: '1:842634282151:web:9169521f06103544330782',
    messagingSenderId: '842634282151',
    projectId: 'out-app-56de7',
    authDomain: 'out-app-56de7.firebaseapp.com',
    storageBucket: 'out-app-56de7.appspot.com',
    measurementId: 'G-MH2M1Y1ZM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipEX55YI8f0h7p7Z_H4vPfwv2Z7xSW_c',
    appId: '1:842634282151:android:e9f38129d6dd199c330782',
    messagingSenderId: '842634282151',
    projectId: 'out-app-56de7',
    storageBucket: 'out-app-56de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_ys5CqGxlWFm2TlANT2tN1aUkp3RREE',
    appId: '1:842634282151:ios:6bea17d2ac0323cd330782',
    messagingSenderId: '842634282151',
    projectId: 'out-app-56de7',
    storageBucket: 'out-app-56de7.appspot.com',
    iosClientId: '842634282151-nleokbhlhbkv3v29sopb5pu0erfpm8pq.apps.googleusercontent.com',
    iosBundleId: 'com.out.app',
  );
}
