/// Flutter icons OutApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OutApp
///      fonts:
///       - asset: fonts/OutApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OutApp {
  OutApp._();

  static const _kFontFam = 'OutApp';
  static const String? _kFontPkg = null;

  static const IconData tableRestaurant =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
